---
- name: Copy Kubernetes manifest template to machine.
  template:
    src: manifest.j2
    dest: "{{ pi_home_dir }}/manifest.yaml"

- name: Install MetalLB.
  shell:
    cmd: "kubectl apply -f {{ pi_home_dir}}/manifest.yaml"

- name: Add secret to encrypt communication between MetalLB speakers.
  shell:
    cmd: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
