---
- name: Secure Raspberry Pi.
  import_tasks: secure.yml
  when: secure_raspberry_pis | bool

- name: Install k3s on master node.
  import_tasks: master.yml
  when: "'master' in group_names"

- name: Install k3s on worker nodes and join them to cluster.
  import_tasks: workers.yml
  when: "'workers' in group_names"

- name: Install Helm on master node.
  import_tasks: helm.yml
  when: "'master' in group_names"

- name: Install MetalLB loadbalancer.
  import_tasks: metallb/main.yml
  when: "'master' in group_names"
